apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: vault
  namespace: carvel-package
spec:
  packageRef:
    refName: vault.itq.io
    versionSelection:
      constraints: 1.13.1
  serviceAccountName: carvel-package-admin-sa
  values:
  - secretRef:
      name: vault-carvel-package-values