---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carvel-package-admin-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carvel-package-admin-sa
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carvel-package-admin-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: carvel-package-admin-cluster-role
subjects:
- kind: ServiceAccount
  name: carvel-package-admin-sa
  namespace: carvel-package

