apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: carvel-package
  annotations:
    kapp.k14s.io/change-group: "workload/cert-manager"
spec:
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 1.10.1+vmware.1-tkg.2
  serviceAccountName: carvel-package-admin-sa

