apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  namespace: carvel-package
  annotations:
    kapp.k14s.io/change-group: "workload/contour"
    kapp.k14s.io/change-rule.0: "upsert after upserting workload/cert-manager"
    kapp.k14s.io/change-rule.1: "upsert after after workload/external-dns"
spec:
  packageRef:
    refName: contour.tanzu.vmware.com
    versionSelection:
      constraints: 1.22.3+vmware.1-tkg.1
  serviceAccountName: carvel-package-admin-sa
  values:
  - secretRef:
      name: contour-values